volumes:
  mysql:
  mysql_config:

services:

  flask-api:
    build:
      context: .
    ports:
    - 80:5000
    volumes:
    - ./app:/usr/src/app
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:5.7.39
    ports:
    - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=p@ssw0rd1
    volumes:
      - mysql:/var/lib/mysql
      - mysql_config:/etc/mysql

